# Generated by Django 5.2.3 on 2025-06-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('next_appointment', models.DateTimeField(blank=True, null=True)),
                ('medications', models.TextField(help_text="Comma-separated list, e.g. 'aspirin,metformin'")),
            ],
        ),
    ]
